version: "3.7"

services:
  proxy-nginx:
    container_name: proxy-nginx
    build:
      context: ./proxy/nginx/
    ports:
      - 80:80
    #restart: always
    volumes:
      - ./proxy/nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - web-nginx
      - api-python

  web-nginx:
    container_name: web-nginx
    build:
      context: ./web/nginx
    #restart: always
    volumes:
      - ./web/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./../source/react:/home

  api-python:
    build:
      context: ./api/python
    command: uvicorn app.main:app --host 0.0.0.0 --port 80 --reload
    volumes:
      - ./../source/python/app:/code/app
    depends_on:
      - api-maria
    environment:
      PMA_HOST: api-maria
      PMA_USERE: fastapi
      PMA_PASSWORD: fastapi

  api-maria:
    image: mariadb:10
    container_name: api-maria
    volumes:
      - ./../data/mariadb:/var/lib/mysql
    environment:
      #MYSQL_TCP_PORT: 3306
      MYSQL_ROOT_USER: root
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: fastapi
      MYSQL_USER: fastapi
      MYSQL_PASSWORD: fastapi
      TZ: Asia/Seoul